export const lightColors = {
  primary: '#FF5C7A',
  primaryLight: '#FF8A9E',
  primaryDark: '#CC3A5A',
  secondary: '#7C4DFF',
  secondaryLight: '#A07EFF',
  secondaryDark: '#5A2DCC',
  success: '#32D74B',
  warning: '#FFD60A',
  error: '#FF3B30',
  info: '#0A84FF',
  background: '#F2F2F7',
  surface: '#FFFFFF',
  surfaceLight: '#FAFAFA',
  surfaceDark: '#E5E5EA',
  text: '#1C1C1E',
  textSecondary: '#636366',
  textTertiary: '#AEAEB2',
  border: '#D1D1D6',
  borderLight: '#E5E5EA',
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
  overlay: 'rgba(0, 0, 0, 0.4)',
  shadow: 'rgba(0, 0, 0, 0.1)',
  minimumContrastText: '#FFFFFF',
  focusIndicator: '#1C1C1E',
  disabledOpacity: 0.38,
} as const;

export const darkColors = {
  primary: '#FF5C7A',
  primaryLight: '#FF8A9E',
  primaryDark: '#CC3A5A',
  secondary: '#7C4DFF',
  secondaryLight: '#A07EFF',
  secondaryDark: '#5A2DCC',
  success: '#32D74B',
  warning: '#FFD60A',
  error: '#FF3B30',
  info: '#0A84FF',
  background: '#0D0D0D',
  surface: '#1C1C1E',
  surfaceLight: '#2C2C2E',
  surfaceDark: '#0A0A0A',
  text: '#FFFFFF',
  textSecondary: '#8E8E93',
  textTertiary: '#636366',
  border: '#38383A',
  borderLight: '#48484A',
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
  overlay: 'rgba(0, 0, 0, 0.6)',
  shadow: 'rgba(0, 0, 0, 0.3)',
  minimumContrastText: '#FFFFFF',
  focusIndicator: '#FFFFFF',
  disabledOpacity: 0.38,
} as const;

export const amoledColors = {
  primary: '#FF5C7A',
  primaryLight: '#FF8A9E',
  primaryDark: '#CC3A5A',
  secondary: '#7C4DFF',
  secondaryLight: '#A07EFF',
  secondaryDark: '#5A2DCC',
  success: '#32D74B',
  warning: '#FFD60A',
  error: '#FF3B30',
  info: '#0A84FF',
  background: '#000000',
  surface: '#0D0D0D',
  surfaceLight: '#1C1C1E',
  surfaceDark: '#000000',
  text: '#FFFFFF',
  textSecondary: '#8E8E93',
  textTertiary: '#636366',
  border: '#1C1C1E',
  borderLight: '#2C2C2E',
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
  overlay: 'rgba(0, 0, 0, 0.7)',
  shadow: 'rgba(0, 0, 0, 0.5)',
  minimumContrastText: '#FFFFFF',
  focusIndicator: '#FFFFFF',
  disabledOpacity: 0.38,
} as const;

export const colors = darkColors;

export type ThemeColors = typeof lightColors;
export type LightColors = typeof lightColors;
export type DarkColors = typeof darkColors;
export type AmoledColors = typeof amoledColors;
