export const Icons = {
  home: 'home',
  workout: 'fitness',
  nutrition: 'restaurant',
  health: 'favorite',
  coach: 'smart-toy',
  social: 'people',
  battle: 'swords',
  analytics: 'bar-chart',
  settings: 'settings',
  profile: 'person',
  premium: 'workspace-premium',

  add: 'add',
  edit: 'edit',
  delete: 'delete',
  save: 'save',
  close: 'close',
  back: 'arrow-back',
  more: 'more-horiz',
  search: 'search',
  filter: 'filter',
  sort: 'sort',
  share: 'share',
  upload: 'upload',
  download: 'download',
  refresh: 'refresh',

  check: 'check',
  error: 'error',
  warning: 'warning',
  info: 'info',
  question: 'help',
  success: 'check-circle',

  running: 'directions-run',
  walking: 'directions-walk',
  cycling: 'directions-bike',
  swimming: 'pool',
  yoga: 'self-improvement',
  strength: 'fitness-center',
  cardio: 'favorite-border',
  stretching: 'accessibility-new',
  heart: 'favorite',
  fire: 'local-fire-department',
  star: 'star',
  trophy: 'emoji-events',
  medal: 'military-tech',
  level: 'trending-up',
  xp: 'bolt',
  energy: 'battery-charging-full',
  water: 'water-drop',
  sleep: 'bedtime',
  sun: 'wb-sunny',
  moon: 'dark-mode',
  calendar: 'calendar-today',
  clock: 'schedule',
  target: 'track-changes',
  notification: 'notifications',
  message: 'message',
  chat: 'chat',
  group: 'groups',
  person: 'person',
  lock: 'lock',
  crown: 'crown',

  food: 'restaurant',
  meal: 'lunch-dining',
  breakfast: 'breakfast-dining',
  lunch: 'lunch-dining',
  dinner: 'dinner-dining',
  snack: 'cookie',
  calories: 'local-fire-department',
  protein: 'egg',
  carbs: 'grain',
  fat: 'oil-barrel',

  placeholder: 'image',
  camera: 'camera-alt',
  microphone: 'mic',
  location: 'location-on',
  qrCode: 'qr-code-scanner',
  timer: 'timer',
  music: 'music-note',
  award: 'workspace-premium',
  gift: 'card-giftcard',
  flash: 'bolt',
  leaderboard: 'leaderboard',

  like: 'thumb-up',
  comment: 'comment',
  friend: 'person-add',
  community: 'groups',
  story: 'auto-stories',

  sword: 'sports-kabaddi',
  shield: 'shield',
  attack: 'whatshot',
  defend: 'verified',
  health_bar: 'favorite-border',

  arrowUp: 'arrow-upward',
  arrowDown: 'arrow-downward',
  arrowLeft: 'arrow-left',
  arrowRight: 'arrow-right',
  menu: 'menu',
  dragHandle: 'drag-handle',
  expandMore: 'expand-more',
  expandLess: 'expand-less',
} as const;

export type IconName = keyof typeof Icons;

export const iconCategories = {
  navigation: ['home', 'workout', 'nutrition', 'health', 'coach', 'social', 'battle', 'analytics', 'settings', 'profile', 'premium'] as IconName[],
  actions: ['add', 'edit', 'delete', 'save', 'close', 'back', 'more', 'search', 'filter', 'sort', 'share', 'upload', 'download', 'refresh'] as IconName[],
  status: ['check', 'error', 'warning', 'info', 'question', 'success'] as IconName[],
  fitness: ['running', 'walking', 'cycling', 'swimming', 'yoga', 'strength', 'cardio', 'stretching', 'heart', 'fire', 'star', 'trophy', 'medal', 'level', 'xp', 'energy', 'water', 'sleep', 'sun', 'moon', 'calendar', 'clock', 'target', 'notification', 'message', 'chat', 'group', 'person', 'lock', 'crown'] as IconName[],
  nutrition: ['food', 'meal', 'breakfast', 'lunch', 'dinner', 'snack', 'calories', 'protein', 'carbs', 'fat'] as IconName[],
  social: ['like', 'comment', 'share', 'friend', 'community', 'story'] as IconName[],
  battle: ['sword', 'shield', 'attack', 'defend', 'health_bar'] as IconName[],
} as const;
