export interface FoodItem {
  id: string;
  name: string;
  brand?: string;
  barcode?: string;
  category: string;
  servingSize: string;
  servingUnit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  sodium?: number;
  potassium?: number;
  cholesterol?: number;
  calcium?: number;
  iron?: number;
  magnesium?: number;
  vitaminA?: number;
  vitaminC?: number;
  vitaminD?: number;
  vitaminE?: number;
  vitaminK?: number;
  niacin?: number;
  folate?: number;
  vitaminB12?: number;
  omega3?: number;
  iodine?: number;
  vitamins?: Record<string, number>;
  minerals?: Record<string, number>;
  ingredients?: string[];
  allergens?: string[];
  verified?: boolean;
  image?: string;
  tags?: string[];
  popularity?: number;
  searchKeywords?: string[];
}