import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface RecipeData {
  name: string;
  description: string;
  mealType: string;
  difficulty: string;
  prepTime: number;
  cookTime: number | null;
  servings: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number | null;
  ingredients: string[];
  steps: string[];
  tags: string[];
}

const RECIPES: RecipeData[] = [
  // ==================== BREAKFAST (15) ====================
  {
    name: 'Protein Pancakes',
    description: 'Fluffy high-protein pancakes perfect for post-workout breakfast',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    calories: 340,
    protein: 30,
    carbs: 35,
    fat: 8,
    fiber: 3,
    ingredients: ['1 scoop whey protein', '1 banana mashed', '2 eggs', '1/2 cup oats', '1/2 tsp baking powder', '1 tsp cinnamon', '1 tbsp coconut oil'],
    steps: ['Mix all ingredients in a bowl until smooth batter forms', 'Heat coconut oil in non-stick pan over medium heat', 'Pour batter in small circles, cook 2-3 min per side', 'Flip when bubbles form on surface', 'Serve with fresh berries and sugar-free syrup'],
    tags: ['protein', 'breakfast', 'pancakes', 'high-protein'],
  },
  {
    name: 'Greek Yogurt Parfait',
    description: 'Layered Greek yogurt parfait with berries and granola',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 310,
    protein: 25,
    carbs: 35,
    fat: 8,
    fiber: 5,
    ingredients: ['200g Greek yogurt nonfat', '1/2 cup mixed berries', '1/4 cup granola', '1 tbsp honey', '1 tbsp chia seeds'],
    steps: ['Layer Greek yogurt in a bowl or glass', 'Add berries, granola, and chia seeds on top', 'Drizzle with honey', 'Serve immediately'],
    tags: ['yogurt', 'parfait', 'breakfast', 'high-protein', 'quick'],
  },
  {
    name: 'Egg White Omelette',
    description: 'Low-calorie egg white omelette packed with vegetables',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    calories: 220,
    protein: 28,
    carbs: 8,
    fat: 9,
    fiber: 3,
    ingredients: ['4 egg whites', '1 whole egg', '1/4 cup diced bell peppers', '1/4 cup spinach', '1 tbsp olive oil', 'Salt and pepper to taste'],
    steps: ['Whisk egg whites and whole egg together', 'Heat olive oil in non-stick pan', 'Saute bell peppers and spinach for 1-2 minutes', 'Pour eggs over vegetables', 'Cook until set, fold and serve'],
    tags: ['eggs', 'omelette', 'low-calorie', 'high-protein', 'breakfast'],
  },
  {
    name: 'Overnight Oats',
    description: 'Make-ahead overnight oats with protein powder',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    calories: 350,
    protein: 25,
    carbs: 45,
    fat: 8,
    fiber: 7,
    ingredients: ['1/2 cup rolled oats', '1 scoop protein powder', '1 cup almond milk', '1 tbsp chia seeds', '1/2 banana sliced', '1 tbsp peanut butter'],
    steps: ['Combine oats, protein powder, chia seeds, and almond milk in a jar', 'Stir well to combine', 'Refrigerate overnight', 'Top with banana slices and peanut butter in the morning', 'Enjoy cold or microwave 30 seconds'],
    tags: ['oats', 'overnight-oats', 'meal-prep', 'breakfast', 'protein'],
  },
  {
    name: 'Avocado Toast with Eggs',
    description: 'Classic avocado toast with poached eggs on sourdough',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    calories: 380,
    protein: 18,
    carbs: 30,
    fat: 22,
    fiber: 7,
    ingredients: ['2 slices sourdough bread', '1 avocado', '2 eggs', '1 tsp red pepper flakes', 'Salt and pepper', '1 tbsp lemon juice'],
    steps: ['Toast bread until golden', 'Mash avocado with lemon juice, salt and pepper', 'Poach eggs in simmering water for 3-4 minutes', 'Spread avocado on toast, top with eggs', 'Sprinkle red pepper flakes and serve'],
    tags: ['avocado', 'toast', 'eggs', 'breakfast', 'healthy-fats'],
  },
  {
    name: 'Protein Smoothie Bowl',
    description: 'Thick smoothie bowl topped with granola and fresh fruit',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    calories: 380,
    protein: 30,
    carbs: 50,
    fat: 7,
    fiber: 8,
    ingredients: ['1 scoop protein powder', '1 frozen banana', '1/2 cup frozen berries', '1/2 cup almond milk', '1 tbsp almond butter', 'Toppings: granola, sliced banana, chia seeds'],
    steps: ['Blend protein powder, frozen banana, berries, almond milk, and almond butter until thick', 'Pour into a bowl', 'Top with granola, sliced banana, and chia seeds', 'Serve immediately with a spoon'],
    tags: ['smoothie-bowl', 'protein', 'breakfast', 'fruit'],
  },
  {
    name: 'Breakfast Burrito',
    description: 'High-protein breakfast burrito with eggs and turkey',
    mealType: 'breakfast',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    calories: 420,
    protein: 32,
    carbs: 35,
    fat: 16,
    fiber: 4,
    ingredients: ['4 eggs', '150g ground turkey', '2 large tortillas', '1/2 cup black beans', '1/4 cup shredded cheese', '1/4 cup salsa', '1 tbsp olive oil'],
    steps: ['Cook ground turkey in olive oil until browned', 'Scramble eggs in separate pan', 'Warm tortillas in dry pan', 'Layer turkey, eggs, black beans, cheese, and salsa on tortillas', 'Roll tightly and serve'],
    tags: ['burrito', 'breakfast', 'eggs', 'turkey', 'high-protein'],
  },
  {
    name: 'Chia Pudding',
    description: 'Creamy chia pudding with vanilla and berries',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    calories: 250,
    protein: 12,
    carbs: 28,
    fat: 10,
    fiber: 12,
    ingredients: ['1/4 cup chia seeds', '1 cup coconut milk', '1 tbsp maple syrup', '1 tsp vanilla extract', '1/2 cup mixed berries'],
    steps: ['Mix chia seeds, coconut milk, maple syrup, and vanilla in a bowl', 'Stir well, refrigerate for at least 4 hours or overnight', 'Stir again after 30 minutes to prevent clumps', 'Serve topped with fresh berries'],
    tags: ['chia', 'pudding', 'breakfast', 'fiber', 'vegan'],
  },
  {
    name: 'Turkey Sausage Scramble',
    description: 'Protein-packed scramble with turkey sausage and vegetables',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    calories: 310,
    protein: 28,
    carbs: 8,
    fat: 18,
    fiber: 2,
    ingredients: ['4 eggs', '2 turkey sausage patties', '1/2 onion diced', '1/2 bell pepper diced', '1 tbsp olive oil', 'Salt and pepper'],
    steps: ['Cook turkey sausage in olive oil, breaking into pieces', 'Add onion and bell pepper, saute 3 minutes', 'Beat eggs and pour over mixture', 'Scramble until eggs are set', 'Season and serve hot'],
    tags: ['eggs', 'turkey', 'scramble', 'breakfast', 'high-protein'],
  },
  {
    name: 'Peanut Butter Protein Toast',
    description: 'Quick high-protein toast with peanut butter and banana',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 3,
    cookTime: 2,
    servings: 1,
    calories: 360,
    protein: 20,
    carbs: 35,
    fat: 16,
    fiber: 5,
    ingredients: ['2 slices whole wheat bread', '2 tbsp peanut butter', '1 banana sliced', '1 tbsp hemp seeds', '1 tsp honey'],
    steps: ['Toast bread until golden', 'Spread peanut butter on each slice', 'Top with banana slices', 'Drizzle honey and sprinkle hemp seeds', 'Serve immediately'],
    tags: ['peanut-butter', 'toast', 'quick', 'breakfast', 'protein'],
  },
  {
    name: 'Ham and Cheese Egg Muffins',
    description: 'Make-ahead egg muffins for easy breakfast meal prep',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 20,
    servings: 6,
    calories: 180,
    protein: 16,
    carbs: 3,
    fat: 11,
    fiber: 0.5,
    ingredients: ['6 eggs', '100g ham diced', '1/2 cup shredded cheddar', '1/4 cup milk', 'Salt and pepper', '1 tbsp chives'],
    steps: ['Preheat oven to 375F', 'Whisk eggs with milk, salt, and pepper', 'Divide ham and cheese among greased muffin tins', 'Pour egg mixture over fillings', 'Bake 18-20 minutes until set', 'Cool and refrigerate up to 5 days'],
    tags: ['eggs', 'meal-prep', 'muffins', 'breakfast', 'high-protein'],
  },
  {
    name: 'Steel Cut Oatmeal with Almonds',
    description: 'Hearty steel cut oats with toasted almonds and berries',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 2,
    cookTime: 25,
    servings: 2,
    calories: 300,
    protein: 10,
    carbs: 48,
    fat: 8,
    fiber: 7,
    ingredients: ['1 cup steel cut oats', '3 cups water', '1/4 cup sliced almonds', '1/2 cup blueberries', '1 tbsp brown sugar', '1/2 tsp cinnamon'],
    steps: ['Bring water to boil, add steel cut oats', 'Reduce heat to low, simmer 20-25 minutes stirring occasionally', 'Toast almonds in dry pan until golden', 'Serve oats topped with almonds, blueberries, brown sugar, and cinnamon'],
    tags: ['oats', 'steel-cut', 'breakfast', 'fiber', 'heart-healthy'],
  },
  {
    name: 'Smoked Salmon Bagel',
    description: 'Classic smoked salmon bagel with cream cheese and capers',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 410,
    protein: 22,
    carbs: 40,
    fat: 18,
    fiber: 2,
    ingredients: ['1 whole wheat bagel', '100g smoked salmon', '2 tbsp cream cheese', '1 tbsp capers', '1/4 red onion sliced', 'Lemon wedge'],
    steps: ['Slice bagel and toast', 'Spread cream cheese on both halves', 'Layer smoked salmon on bottom half', 'Top with capers and red onion', 'Squeeze lemon juice and close bagel'],
    tags: ['salmon', 'bagel', 'breakfast', 'seafood', 'protein'],
  },
  {
    name: 'Banana Walnut Muffins',
    description: 'Healthy banana walnut muffins made with whole wheat flour',
    mealType: 'breakfast',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 22,
    servings: 12,
    calories: 190,
    protein: 5,
    carbs: 28,
    fat: 7,
    fiber: 3,
    ingredients: ['3 ripe bananas', '1/3 cup coconut oil', '1/2 cup honey', '2 eggs', '1 tsp vanilla', '1.5 cups whole wheat flour', '1 tsp baking soda', '1/2 cup chopped walnuts', '1/2 tsp salt'],
    steps: ['Preheat oven to 350F, grease muffin tin', 'Mash bananas, mix with oil, honey, eggs, and vanilla', 'Combine flour, baking soda, salt in separate bowl', 'Mix wet and dry ingredients, fold in walnuts', 'Divide batter into muffin cups', 'Bake 20-22 minutes until toothpick comes clean'],
    tags: ['banana', 'muffins', 'breakfast', 'meal-prep'],
  },
  {
    name: 'Tofu Scramble',
    description: 'Vegan tofu scramble with vegetables and turmeric',
    mealType: 'breakfast',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    calories: 220,
    protein: 16,
    carbs: 12,
    fat: 14,
    fiber: 4,
    ingredients: ['300g firm tofu', '1 tbsp olive oil', '1/2 onion diced', '1/2 bell pepper diced', '1 tsp turmeric', '1/2 tsp cumin', '1/4 cup nutritional yeast', 'Salt and pepper'],
    steps: ['Press tofu and crumble into chunks', 'Heat oil, saute onion and pepper 3 minutes', 'Add tofu, turmeric, cumin, and nutritional yeast', 'Cook 5-7 minutes until heated through', 'Season and serve with toast'],
    tags: ['tofu', 'vegan', 'breakfast', 'scramble', 'plant-protein'],
  },

  // ==================== LUNCH (15) ====================
  {
    name: 'Grilled Chicken Caesar Salad',
    description: 'Classic Caesar salad with grilled chicken breast',
    mealType: 'lunch',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 12,
    servings: 2,
    calories: 380,
    protein: 40,
    carbs: 12,
    fat: 20,
    fiber: 4,
    ingredients: ['2 chicken breasts', '1 head romaine lettuce', '1/4 cup parmesan shaved', '1/4 cup Caesar dressing', '1 cup croutons', '1 tbsp olive oil', 'Salt and pepper'],
    steps: ['Season chicken with salt and pepper', 'Grill chicken 6 minutes per side until cooked through', 'Chop romaine lettuce and toss with Caesar dressing', 'Slice chicken and place on salad', 'Top with parmesan shavings and croutons'],
    tags: ['chicken', 'caesar', 'salad', 'lunch', 'high-protein'],
  },
  {
    name: 'Turkey and Avocado Wrap',
    description: 'Fresh turkey wrap with avocado, lettuce, and tomato',
    mealType: 'lunch',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    calories: 420,
    protein: 30,
    carbs: 30,
    fat: 20,
    fiber: 6,
    ingredients: ['1 large tortilla wrap', '150g sliced turkey breast', '1/2 avocado sliced', '1/4 cup lettuce', '1/4 tomato sliced', '1 tbsp mustard', '1 slice Swiss cheese'],
    steps: ['Lay tortilla flat, spread mustard', 'Layer turkey, cheese, avocado, lettuce, and tomato', 'Fold sides in, roll tightly from bottom', 'Cut in half and serve'],
    tags: ['turkey', 'wrap', 'lunch', 'avocado', 'high-protein'],
  },
  {
    name: 'Quinoa Buddha Bowl',
    description: 'Nutritious Buddha bowl with quinoa, roasted vegetables, and tahini',
    mealType: 'lunch',
    difficulty: 'intermediate',
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    calories: 420,
    protein: 15,
    carbs: 50,
    fat: 18,
    fiber: 10,
    ingredients: ['1 cup quinoa', '1 sweet potato cubed', '1 can chickpeas', '2 cups kale', '1/4 cup tahini', '2 tbsp lemon juice', '1 tbsp olive oil', 'Salt and pepper'],
    steps: ['Cook quinoa according to package directions', 'Toss sweet potato and chickpeas with olive oil, roast at 400F for 20 minutes', 'Massage kale with olive oil and lemon juice', 'Whisk tahini with lemon juice and water for dressing', 'Assemble bowls with quinoa, vegetables, and drizzle dressing'],
    tags: ['quinoa', 'vegan', 'buddha-bowl', 'lunch', 'meal-prep'],
  },
  {
    name: 'Tuna Salad Stuffed Avocado',
    description: 'Healthy tuna salad served in avocado boats',
    mealType: 'lunch',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    calories: 350,
    protein: 28,
    carbs: 8,
    fat: 22,
    fiber: 7,
    ingredients: ['2 cans tuna in water', '2 avocados', '2 tbsp Greek yogurt', '1 tbsp lemon juice', '1/4 cup diced celery', '1 tbsp fresh dill', 'Salt and pepper'],
    steps: ['Drain tuna and mix with Greek yogurt, lemon juice, celery, and dill', 'Halve avocados and remove pits', 'Scoop tuna salad into avocado halves', 'Season with salt and pepper, serve'],
    tags: ['tuna', 'avocado', 'lunch', 'high-protein', 'low-carb'],
  },
  {
    name: 'Chicken Soba Noodle Bowl',
    description: 'Asian-inspired soba noodle bowl with chicken and vegetables',
    mealType: 'lunch',
    difficulty: 'intermediate',
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    calories: 450,
    protein: 35,
    carbs: 50,
    fat: 12,
    fiber: 5,
    ingredients: ['200g soba noodles', '2 chicken breasts', '1 cup broccoli florets', '1 carrot julienned', '3 tbsp soy sauce', '1 tbsp sesame oil', '1 tbsp ginger grated', '1 clove garlic'],
    steps: ['Cook soba noodles according to package, drain', 'Season chicken, grill 6 minutes per side, slice', 'Blanch broccoli and carrot in boiling water 2 minutes', 'Whisk soy sauce, sesame oil, ginger, and garlic for dressing', 'Toss noodles with vegetables and dressing, top with chicken'],
    tags: ['chicken', 'soba', 'noodles', 'asian', 'lunch'],
  },
  {
    name: 'Black Bean Soup',
    description: 'Hearty black bean soup with lime and cilantro',
    mealType: 'lunch',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    calories: 280,
    protein: 14,
    carbs: 45,
    fat: 5,
    fiber: 15,
    ingredients: ['2 cans black beans', '1 onion diced', '3 cloves garlic', '1 tsp cumin', '1 tsp chili powder', '4 cups vegetable broth', '1 lime', 'Fresh cilantro'],
    steps: ['Saute onion and garlic in olive oil until soft', 'Add cumin and chili powder, cook 1 minute', 'Add beans and broth, bring to boil', 'Simmer 20 minutes', 'Blend half the soup for creaminess', 'Serve with lime juice and cilantro'],
    tags: ['black-beans', 'soup', 'vegan', 'lunch', 'fiber'],
  },
  {
    name: 'Grilled Salmon Salad',
    description: 'Fresh salad with grilled salmon, avocado, and citrus vinaigrette',
    mealType: 'lunch',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    calories: 410,
    protein: 35,
    carbs: 12,
    fat: 26,
    fiber: 4,
    ingredients: ['2 salmon fillets', '4 cups mixed greens', '1 avocado sliced', '1/2 cup cherry tomatoes', '1/4 cup red onion', '2 tbsp olive oil', '1 tbsp lemon juice', 'Salt and pepper'],
    steps: ['Season salmon with salt and pepper', 'Grill salmon 4 minutes per side', 'Toss greens with olive oil and lemon juice', 'Top with sliced avocado, tomatoes, and onion', 'Place salmon on salad and serve'],
    tags: ['salmon', 'salad', 'lunch', 'omega-3', 'high-protein'],
  },
  {
    name: 'Lentil and Vegetable Soup',
    description: 'Hearty lentil soup with carrots, celery, and spinach',
    mealType: 'lunch',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    calories: 240,
    protein: 14,
    carbs: 38,
    fat: 3,
    fiber: 14,
    ingredients: ['1 cup dried lentils', '2 carrots diced', '2 celery stalks diced', '1 onion diced', '3 cloves garlic', '1 can diced tomatoes', '4 cups vegetable broth', '2 cups spinach', '1 tsp thyme'],
    steps: ['Saute onion, garlic, carrots, and celery until soft', 'Add lentils, tomatoes, broth, and thyme', 'Bring to boil, reduce heat and simmer 25 minutes', 'Add spinach and cook until wilted', 'Season and serve hot'],
    tags: ['lentils', 'soup', 'vegan', 'lunch', 'meal-prep', 'fiber'],
  },
  {
    name: 'Chicken Pita Sandwich',
    description: 'Mediterranean chicken pita with tzatziki sauce',
    mealType: 'lunch',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    calories: 400,
    protein: 35,
    carbs: 35,
    fat: 14,
    fiber: 3,
    ingredients: ['2 chicken breasts', '2 whole wheat pitas', '1/2 cup tzatziki sauce', '1/2 cup lettuce', '1/2 tomato sliced', '1/4 red onion', '1 tsp oregano', '1 tbsp olive oil'],
    steps: ['Season chicken with oregano, salt, pepper', 'Grill chicken 6 minutes per side, slice thin', 'Warm pitas in dry pan', 'Spread tzatziki inside pitas', 'Fill with chicken, lettuce, tomato, and onion'],
    tags: ['chicken', 'pita', 'mediterranean', 'lunch', 'protein'],
  },
  {
    name: 'Shrimp Stir Fry',
    description: 'Quick shrimp stir fry with vegetables and brown rice',
    mealType: 'lunch',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    calories: 380,
    protein: 30,
    carbs: 40,
    fat: 10,
    fiber: 4,
    ingredients: ['300g shrimp peeled', '2 cups mixed vegetables', '1 cup cooked brown rice', '3 tbsp soy sauce', '1 tbsp sesame oil', '1 tsp ginger', '2 cloves garlic'],
    steps: ['Heat sesame oil in wok over high heat', 'Cook shrimp 2 minutes per side, remove', 'Stir fry vegetables with garlic and ginger 3 minutes', 'Add rice and soy sauce, stir 2 minutes', 'Return shrimp, toss and serve'],
    tags: ['shrimp', 'stir-fry', 'asian', 'lunch', 'seafood'],
  },
  {
    name: 'Caprese Panini',
    description: 'Grilled panini with mozzarella, tomato, and basil',
    mealType: 'lunch',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    calories: 420,
    protein: 20,
    carbs: 35,
    fat: 22,
    fiber: 3,
    ingredients: ['2 slices sourdough bread', '100g fresh mozzarella', '1 tomato sliced', 'Fresh basil leaves', '1 tbsp balsamic glaze', '1 tbsp olive oil'],
    steps: ['Brush bread with olive oil', 'Layer mozzarella, tomato, and basil between bread', 'Grill in panini press or skillet 4 minutes per side', 'Drizzle with balsamic glaze', 'Cut and serve hot'],
    tags: ['panini', 'caprese', 'lunch', 'mozzarella', 'italian'],
  },
  {
    name: 'Beef and Broccoli Stir Fry',
    description: 'Classic beef and broccoli in a savory sauce',
    mealType: 'lunch',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 12,
    servings: 2,
    calories: 420,
    protein: 35,
    carbs: 30,
    fat: 18,
    fiber: 4,
    ingredients: ['300g flank steak sliced thin', '2 cups broccoli florets', '3 tbsp soy sauce', '1 tbsp oyster sauce', '1 tsp sesame oil', '1 tbsp cornstarch', '2 cloves garlic', '1 tbsp ginger'],
    steps: ['Mix soy sauce, oyster sauce, cornstarch', 'Sear beef in hot oil 2 minutes, remove', 'Stir fry broccoli, garlic, and ginger 3 minutes', 'Add sauce and beef back to pan', 'Cook until sauce thickens, serve over rice'],
    tags: ['beef', 'broccoli', 'stir-fry', 'lunch', 'asian'],
  },
  {
    name: 'Mediterranean Chickpea Salad',
    description: 'Fresh chickpea salad with cucumber, tomato, and feta',
    mealType: 'lunch',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    calories: 320,
    protein: 12,
    carbs: 35,
    fat: 15,
    fiber: 9,
    ingredients: ['1 can chickpeas', '1 cucumber diced', '1 cup cherry tomatoes halved', '1/2 cup feta crumbled', '1/4 cup kalamata olives', '2 tbsp olive oil', '1 tbsp lemon juice', '1 tsp oregano'],
    steps: ['Rinse and drain chickpeas', 'Combine all vegetables in a large bowl', 'Add feta and olives', 'Whisk olive oil, lemon juice, and oregano for dressing', 'Toss and serve cold'],
    tags: ['chickpeas', 'mediterranean', 'salad', 'lunch', 'vegan-option'],
  },
  {
    name: 'Turkey Meatballs with Marinara',
    description: 'Lean turkey meatballs served with marinara sauce',
    mealType: 'lunch',
    difficulty: 'intermediate',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 340,
    protein: 30,
    carbs: 20,
    fat: 16,
    fiber: 4,
    ingredients: ['500g ground turkey', '1/2 cup breadcrumbs', '1 egg', '2 cloves garlic minced', '1/4 cup parmesan', '1 tsp Italian seasoning', '2 cups marinara sauce'],
    steps: ['Mix turkey, breadcrumbs, egg, garlic, parmesan, and seasoning', 'Form into 16 meatballs', 'Brown meatballs in olive oil on all sides', 'Add marinara sauce, cover and simmer 20 minutes', 'Serve over pasta or zucchini noodles'],
    tags: ['turkey', 'meatballs', 'italian', 'lunch', 'high-protein'],
  },
  {
    name: 'Asian Chicken Lettuce Wraps',
    description: 'PF Changs-style chicken lettuce wraps',
    mealType: 'lunch',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    calories: 290,
    protein: 28,
    carbs: 12,
    fat: 14,
    fiber: 3,
    ingredients: ['300g ground chicken', '1 head butter lettuce', '1/4 cup water chestnuts', '2 tbsp soy sauce', '1 tbsp rice vinegar', '1 tsp sesame oil', '1 clove garlic', '1 tsp ginger', '2 green onions'],
    steps: ['Brown ground chicken in sesame oil', 'Add garlic, ginger, and water chestnuts, cook 2 minutes', 'Add soy sauce and rice vinegar', 'Spoon mixture into lettuce cups', 'Garnish with green onions and serve'],
    tags: ['chicken', 'lettuce-wraps', 'asian', 'lunch', 'low-carb'],
  },

  // ==================== DINNER (15) ====================
  {
    name: 'Grilled Steak with Roasted Asparagus',
    description: 'Perfectly grilled ribeye steak with roasted asparagus and sweet potato',
    mealType: 'dinner',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    calories: 520,
    protein: 42,
    carbs: 30,
    fat: 26,
    fiber: 6,
    ingredients: ['2 ribeye steaks', '1 bunch asparagus', '1 sweet potato', '2 tbsp olive oil', 'Salt and pepper', '2 cloves garlic', '1 tsp rosemary'],
    steps: ['Season steaks with salt, pepper, garlic, and rosemary', 'Preheat oven to 400F', 'Cube sweet potato, toss with oil, roast 20 minutes', 'Add asparagus to oven for last 10 minutes', 'Grill steaks 4-5 minutes per side for medium-rare', 'Rest steak 5 minutes and serve'],
    tags: ['steak', 'beef', 'dinner', 'high-protein', 'whole30'],
  },
  {
    name: 'Baked Salmon with Quinoa',
    description: 'Lemon dill salmon with fluffy quinoa and steamed broccoli',
    mealType: 'dinner',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    calories: 480,
    protein: 40,
    carbs: 35,
    fat: 18,
    fiber: 5,
    ingredients: ['2 salmon fillets', '1 cup quinoa', '2 cups broccoli', '1 lemon', '2 tbsp dill', '2 tbsp olive oil', 'Salt and pepper'],
    steps: ['Preheat oven to 375F', 'Season salmon with lemon juice, dill, oil, salt, pepper', 'Bake salmon 15-18 minutes', 'Cook quinoa according to package', 'Steam broccoli 5 minutes', 'Plate and serve'],
    tags: ['salmon', 'quinoa', 'dinner', 'omega-3', 'high-protein'],
  },
  {
    name: 'Chicken Marsala',
    description: 'Classic Italian chicken marsala with mushrooms',
    mealType: 'dinner',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    calories: 380,
    protein: 35,
    carbs: 10,
    fat: 20,
    fiber: 1,
    ingredients: ['4 chicken breasts', '2 cups mushrooms sliced', '1 cup marsala wine', '1/2 cup chicken broth', '3 tbsp butter', '2 tbsp flour', '2 cloves garlic', 'Fresh parsley'],
    steps: ['Pound chicken to even thickness, season', 'Dredge in flour, brown in butter 4 min per side, remove', 'Saute mushrooms and garlic 5 minutes', 'Add marsala wine and broth, simmer 5 minutes', 'Return chicken, cook 10 minutes until sauce thickens', 'Garnish with parsley and serve'],
    tags: ['chicken', 'marsala', 'italian', 'dinner', 'date-night'],
  },
  {
    name: 'Beef Chili',
    description: 'Hearty beef chili with beans and spices',
    mealType: 'dinner',
    difficulty: 'beginner',
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    calories: 380,
    protein: 30,
    carbs: 35,
    fat: 14,
    fiber: 10,
    ingredients: ['500g ground beef 85/15', '1 onion diced', '1 bell pepper diced', '3 cloves garlic', '2 cans diced tomatoes', '1 can kidney beans', '1 can black beans', '2 tbsp chili powder', '1 tsp cumin', '1 tsp paprika'],
    steps: ['Brown ground beef in large pot', 'Add onion, pepper, garlic, cook 5 minutes', 'Add spices and cook 1 minute', 'Add tomatoes and beans, bring to boil', 'Simmer 30-40 minutes', 'Serve with toppings of choice'],
    tags: ['beef', 'chili', 'dinner', 'meal-prep', 'comfort-food'],
  },
  {
    name: 'Chicken Fajitas',
    description: 'Sizzling chicken fajitas with peppers and onions',
    mealType: 'dinner',
    difficulty: 'beginner',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    calories: 400,
    protein: 35,
    carbs: 30,
    fat: 16,
    fiber: 4,
    ingredients: ['4 chicken breasts sliced', '2 bell peppers sliced', '1 onion sliced', '2 tbsp fajita seasoning', '2 tbsp olive oil', '8 tortillas', '1/2 cup sour cream', '1/4 cup cilantro', '1 lime'],
    steps: ['Toss chicken with fajita seasoning', 'Sear chicken in hot oil 5 minutes, remove', 'Cook peppers and onions until charred', 'Return chicken to pan, heat through', 'Serve on warm tortillas with toppings'],
    tags: ['chicken', 'fajitas', 'mexican', 'dinner', 'high-protein'],
  },
  {
    name: 'Baked Cod with Vegetables',
    description: 'Light baked cod with cherry tomatoes and olives',
    mealType: 'dinner',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 18,
    servings: 2,
    calories: 300,
    protein: 35,
    carbs: 8,
    fat: 14,
    fiber: 2,
    ingredients: ['2 cod fillets', '1 cup cherry tomatoes', '1/4 cup olives', '2 tbsp olive oil', '1 lemon', '2 cloves garlic', '1 tsp oregano', 'Salt and pepper'],
    steps: ['Preheat oven to 400F', 'Place cod in baking dish with tomatoes and olives', 'Drizzle olive oil, lemon juice, garlic, and oregano', 'Bake 15-18 minutes until fish flakes', 'Serve with lemon wedges'],
    tags: ['cod', 'fish', 'dinner', 'light', 'mediterranean'],
  },
  {
    name: 'Pork Tenderloin with Roasted Vegetables',
    description: 'Herb-crusted pork tenderloin with roasted root vegetables',
    mealType: 'dinner',
    difficulty: 'intermediate',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    calories: 420,
    protein: 38,
    carbs: 25,
    fat: 18,
    fiber: 5,
    ingredients: ['500g pork tenderloin', '2 carrots', '2 parsnips', '1 sweet potato', '1 red onion', '2 tbsp olive oil', '2 cloves garlic', '1 tsp rosemary', '1 tsp thyme', 'Salt and pepper'],
    steps: ['Preheat oven to 425F', 'Season pork with herbs, salt, pepper', 'Chop vegetables into chunks, toss with oil', 'Roast vegetables 15 minutes', 'Add pork to pan, roast 15-18 more minutes', 'Rest pork 5 minutes, slice and serve'],
    tags: ['pork', 'tenderloin', 'dinner', 'roasted', 'whole-food'],
  },
  {
    name: 'Vegetable Stir Fry with Tofu',
    description: 'Crispy tofu and vegetable stir fry in garlic sauce',
    mealType: 'dinner',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    calories: 320,
    protein: 18,
    carbs: 28,
    fat: 16,
    fiber: 6,
    ingredients: ['300g firm tofu', '2 cups mixed vegetables', '3 tbsp soy sauce', '1 tbsp sesame oil', '1 tbsp cornstarch', '2 cloves garlic', '1 tsp ginger', '1 tbsp rice vinegar'],
    steps: ['Press and cube tofu, toss with cornstarch', 'Fry tofu in oil until golden on all sides', 'Add garlic, ginger, and vegetables, stir fry 5 minutes', 'Add soy sauce and rice vinegar', 'Toss and serve over rice'],
    tags: ['tofu', 'stir-fry', 'vegan', 'dinner', 'asian'],
  },
  {
    name: 'Lamb Chops with Mint Sauce',
    description: 'Pan-seared lamb chops with fresh mint sauce',
    mealType: 'dinner',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 12,
    servings: 2,
    calories: 450,
    protein: 35,
    carbs: 5,
    fat: 32,
    fiber: 1,
    ingredients: ['8 lamb chops', '1/4 cup fresh mint', '2 tbsp red wine vinegar', '1 tbsp honey', '2 tbsp olive oil', '3 cloves garlic', 'Salt and pepper'],
    steps: ['Season lamb with garlic, salt, pepper', 'Blend mint, vinegar, honey for sauce', 'Sear lamb in hot oil 3-4 minutes per side', 'Rest lamb 5 minutes', 'Drizzle mint sauce and serve'],
    tags: ['lamb', 'chops', 'dinner', 'date-night', 'premium'],
  },
  {
    name: 'Turkey Bolognese',
    description: 'Lean turkey bolognese sauce over whole wheat pasta',
    mealType: 'dinner',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    calories: 450,
    protein: 32,
    carbs: 50,
    fat: 12,
    fiber: 6,
    ingredients: ['500g ground turkey', '1 onion diced', '2 carrots grated', '2 cloves garlic', '1 can crushed tomatoes', '1/2 cup red wine', '2 tbsp tomato paste', '1 tsp Italian seasoning', '400g whole wheat pasta'],
    steps: ['Brown turkey in large pot', 'Add onion, carrots, garlic, cook 5 minutes', 'Add tomato paste, cook 2 minutes', 'Add tomatoes, wine, seasoning, simmer 25 minutes', 'Cook pasta al dente', 'Serve sauce over pasta with parmesan'],
    tags: ['turkey', 'bolognese', 'pasta', 'dinner', 'italian'],
  },
  {
    name: 'Shrimp Tacos',
    description: 'Crispy shrimp tacos with mango salsa and spicy mayo',
    mealType: 'dinner',
    difficulty: 'intermediate',
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    calories: 420,
    protein: 28,
    carbs: 35,
    fat: 18,
    fiber: 3,
    ingredients: ['300g shrimp', '4 corn tortillas', '1 mango diced', '1/4 cup red onion', '1 jalapeno minced', '1/4 cup cilantro', '2 tbsp mayo', '1 tsp sriracha', '1 lime', '1 tbsp olive oil'],
    steps: ['Mix mango, onion, jalapeno, cilantro, lime juice for salsa', 'Mix mayo and sriracha for spicy sauce', 'Season shrimp with salt and chili powder', 'Sear shrimp in oil 2 minutes per side', 'Assemble tacos with shrimp, salsa, and spicy mayo'],
    tags: ['shrimp', 'tacos', 'mexican', 'dinner', 'seafood'],
  },
  {
    name: 'Stuffed Bell Peppers',
    description: 'Bell peppers stuffed with seasoned ground beef and rice',
    mealType: 'dinner',
    difficulty: 'intermediate',
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    calories: 380,
    protein: 28,
    carbs: 30,
    fat: 16,
    fiber: 5,
    ingredients: ['4 bell peppers', '400g ground beef', '1 cup cooked rice', '1 onion diced', '1 can diced tomatoes', '1 cup shredded cheese', '1 tsp Italian seasoning', '2 cloves garlic'],
    steps: ['Preheat oven to 375F', 'Cut tops off peppers, remove seeds', 'Brown beef with onion and garlic', 'Mix beef with rice, tomatoes, half the cheese, seasoning', 'Stuff peppers with mixture', 'Top with remaining cheese, bake 30-35 minutes'],
    tags: ['beef', 'stuffed-peppers', 'dinner', 'comfort-food'],
  },
  {
    name: 'Thai Green Curry',
    description: 'Aromatic Thai green curry with chicken and vegetables',
    mealType: 'dinner',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    calories: 400,
    protein: 30,
    carbs: 25,
    fat: 22,
    fiber: 4,
    ingredients: ['400g chicken thighs sliced', '2 tbsp green curry paste', '1 can coconut milk', '1 cup bamboo shoots', '1 bell pepper sliced', '1 cup green beans', '1 tbsp fish sauce', '1 tbsp brown sugar', '1/4 cup basil'],
    steps: ['Heat curry paste in oil until fragrant', 'Add chicken, cook 5 minutes', 'Add coconut milk, bamboo shoots, bell pepper, green beans', 'Simmer 15 minutes until vegetables are tender', 'Season with fish sauce and sugar', 'Garnish with basil and serve over rice'],
    tags: ['chicken', 'thai', 'curry', 'dinner', 'asian'],
  },
  {
    name: 'Shepherds Pie',
    description: 'Classic shepherds pie with ground lamb and mashed potatoes',
    mealType: 'dinner',
    difficulty: 'intermediate',
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    calories: 450,
    protein: 28,
    carbs: 35,
    fat: 22,
    fiber: 4,
    ingredients: ['500g ground lamb', '1 onion diced', '2 carrots diced', '1 cup peas', '2 tbsp tomato paste', '1 cup beef broth', '1 tsp rosemary', '4 large potatoes', '3 tbsp butter', '1/4 cup milk'],
    steps: ['Boil potatoes until tender, mash with butter and milk', 'Brown lamb with onion and carrots', 'Add tomato paste, broth, peas, rosemary, simmer 15 minutes', 'Transfer to baking dish, top with mashed potatoes', 'Bake at 400F for 25 minutes until golden'],
    tags: ['lamb', 'shepherds-pie', 'dinner', 'comfort-food', 'british'],
  },
  {
    name: 'Chicken Teriyaki',
    description: 'Homemade chicken teriyaki with steamed rice and vegetables',
    mealType: 'dinner',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    calories: 450,
    protein: 38,
    carbs: 50,
    fat: 8,
    fiber: 3,
    ingredients: ['2 chicken breasts', '1 cup jasmine rice', '1 cup broccoli', '1/2 cup soy sauce', '1/4 cup honey', '2 tbsp rice vinegar', '1 tsp ginger', '1 clove garlic', '1 tbsp cornstarch'],
    steps: ['Mix soy sauce, honey, vinegar, ginger, garlic for sauce', 'Cook rice according to package', 'Sear chicken in oil 5 minutes per side', 'Add sauce and simmer 5 minutes', 'Remove chicken, thicken sauce with cornstarch slurry', 'Slice chicken and serve over rice with broccoli'],
    tags: ['chicken', 'teriyaki', 'japanese', 'dinner', 'high-protein'],
  },

  // ==================== SNACKS (10) ====================
  {
    name: 'Protein Energy Balls',
    description: 'No-bake protein energy balls with peanut butter and oats',
    mealType: 'snack',
    difficulty: 'beginner',
    prepTime: 15,
    cookTime: 0,
    servings: 12,
    calories: 120,
    protein: 7,
    carbs: 14,
    fat: 5,
    fiber: 2,
    ingredients: ['1 cup rolled oats', '1/2 cup peanut butter', '1/3 cup honey', '1 scoop protein powder', '1/4 cup dark chocolate chips', '1 tbsp chia seeds'],
    steps: ['Combine all ingredients in a bowl', 'Mix thoroughly until well combined', 'Roll into 12 balls', 'Refrigerate for 30 minutes before eating', 'Store in fridge up to 2 weeks'],
    tags: ['protein-balls', 'snack', 'no-bake', 'meal-prep', 'high-protein'],
  },
  {
    name: 'Hummus with Veggie Sticks',
    description: 'Classic homemade hummus with fresh vegetable crudites',
    mealType: 'snack',
    difficulty: 'beginner',
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    calories: 180,
    protein: 6,
    carbs: 20,
    fat: 9,
    fiber: 6,
    ingredients: ['1 can chickpeas', '2 tbsp tahini', '1 tbsp lemon juice', '1 clove garlic', '2 tbsp olive oil', '1/2 tsp cumin', 'Assorted vegetable sticks'],
    steps: ['Blend chickpeas, tahini, lemon juice, garlic, oil, cumin in food processor', 'Add water as needed for consistency', 'Season with salt', 'Serve with carrot, celery, cucumber and bell pepper sticks'],
    tags: ['hummus', 'chickpeas', 'snack', 'vegan', 'healthy'],
  },
  {
    name: 'Greek Yogurt Protein Bowl',
    description: 'High-protein Greek yogurt bowl with toppings',
    mealType: 'snack',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 220,
    protein: 22,
    carbs: 18,
    fat: 8,
    fiber: 4,
    ingredients: ['200g Greek yogurt', '1 tbsp honey', '1/2 cup mixed berries', '1 tbsp almonds sliced', '1 tbsp chia seeds'],
    steps: ['Scoop yogurt into a bowl', 'Drizzle honey on top', 'Add berries, almonds, and chia seeds', 'Enjoy immediately'],
    tags: ['yogurt', 'protein', 'snack', 'quick', 'healthy'],
  },
  {
    name: 'Apple Slices with Almond Butter',
    description: 'Simple apple slices with almond butter and cinnamon',
    mealType: 'snack',
    difficulty: 'beginner',
    prepTime: 3,
    cookTime: 0,
    servings: 1,
    calories: 220,
    protein: 5,
    carbs: 28,
    fat: 11,
    fiber: 6,
    ingredients: ['1 apple sliced', '2 tbsp almond butter', '1/2 tsp cinnamon'],
    steps: ['Slice apple into wedges', 'Serve with almond butter for dipping', 'Sprinkle with cinnamon'],
    tags: ['apple', 'almond-butter', 'snack', 'quick', 'healthy'],
  },
  {
    name: 'Roasted Chickpeas',
    description: 'Crispy roasted chickpeas seasoned with spices',
    mealType: 'snack',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 30,
    servings: 4,
    calories: 140,
    protein: 7,
    carbs: 18,
    fat: 5,
    fiber: 6,
    ingredients: ['1 can chickpeas', '1 tbsp olive oil', '1 tsp cumin', '1/2 tsp paprika', '1/4 tsp cayenne', 'Salt'],
    steps: ['Preheat oven to 400F', 'Drain and dry chickpeas thoroughly', 'Toss with oil and spices', 'Spread on baking sheet', 'Roast 25-30 minutes until crispy, shaking halfway'],
    tags: ['chickpeas', 'roasted', 'snack', 'vegan', 'crispy'],
  },
  {
    name: 'Cottage Cheese and Pineapple Bowl',
    description: 'High-protein cottage cheese bowl with pineapple',
    mealType: 'snack',
    difficulty: 'beginner',
    prepTime: 3,
    cookTime: 0,
    servings: 1,
    calories: 180,
    protein: 18,
    carbs: 14,
    fat: 5,
    fiber: 1,
    ingredients: ['200g cottage cheese', '1/2 cup pineapple chunks', '1 tbsp chopped pecans'],
    steps: ['Scoop cottage cheese into a bowl', 'Top with pineapple chunks', 'Sprinkle pecans on top', 'Enjoy immediately'],
    tags: ['cottage-cheese', 'pineapple', 'snack', 'high-protein', 'quick'],
  },
  {
    name: 'Edamame with Sea Salt',
    description: 'Steamed edamame sprinkled with sea salt',
    mealType: 'snack',
    difficulty: 'beginner',
    prepTime: 2,
    cookTime: 5,
    servings: 2,
    calories: 120,
    protein: 11,
    carbs: 9,
    fat: 5,
    fiber: 5,
    ingredients: ['2 cups frozen edamame in pods', '1 tsp sea salt', '1 tsp sesame oil'],
    steps: ['Steam or boil edamame for 5 minutes', 'Drain and toss with sesame oil and sea salt', 'Serve warm'],
    tags: ['edamame', 'soy', 'snack', 'protein', 'vegan'],
  },
  {
    name: 'Rice Cake with Avocado and Everything Seasoning',
    description: 'Crunchy rice cake topped with avocado and seasoning',
    mealType: 'snack',
    difficulty: 'beginner',
    prepTime: 3,
    cookTime: 0,
    servings: 1,
    calories: 150,
    protein: 3,
    carbs: 15,
    fat: 9,
    fiber: 4,
    ingredients: ['2 rice cakes', '1/2 avocado', 'Everything bagel seasoning', 'Red pepper flakes'],
    steps: ['Mash avocado and spread on rice cakes', 'Sprinkle with everything seasoning and red pepper flakes', 'Serve immediately'],
    tags: ['rice-cakes', 'avocado', 'snack', 'quick', 'healthy'],
  },
  {
    name: 'Banana Protein Muffins',
    description: 'Protein-packed banana muffins made with oat flour',
    mealType: 'snack',
    difficulty: 'intermediate',
    prepTime: 10,
    cookTime: 18,
    servings: 10,
    calories: 160,
    protein: 12,
    carbs: 22,
    fat: 4,
    fiber: 3,
    ingredients: ['2 ripe bananas', '2 scoops protein powder', '1 cup oat flour', '2 eggs', '1/4 cup honey', '1 tsp baking powder', '1/2 tsp cinnamon', '1/4 cup dark chocolate chips'],
    steps: ['Preheat oven to 350F', 'Mash bananas, mix with eggs and honey', 'Combine protein powder, oat flour, baking powder, cinnamon', 'Mix wet and dry ingredients, fold in chocolate chips', 'Divide into muffin tin, bake 16-18 minutes'],
    tags: ['banana', 'protein-muffins', 'snack', 'meal-prep'],
  },
  {
    name: 'Chocolate Peanut Butter Protein Shake',
    description: 'Thick and creamy chocolate peanut butter protein shake',
    mealType: 'snack',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 320,
    protein: 30,
    carbs: 25,
    fat: 12,
    fiber: 4,
    ingredients: ['1 scoop chocolate protein powder', '1 tbsp peanut butter', '1 cup almond milk', '1/2 banana frozen', '1/2 cup ice'],
    steps: ['Combine all ingredients in blender', 'Blend until smooth and creamy', 'Pour into glass and enjoy'],
    tags: ['protein-shake', 'chocolate', 'peanut-butter', 'snack', 'post-workout'],
  },

  // ==================== POST-WORKOUT (10) ====================
  {
    name: 'Post-Workout Protein Shake',
    description: 'Quick post-workout shake with whey protein and dextrose',
    mealType: 'post-workout',
    difficulty: 'beginner',
    prepTime: 3,
    cookTime: 0,
    servings: 1,
    calories: 250,
    protein: 30,
    carbs: 30,
    fat: 2,
    fiber: 0,
    ingredients: ['1.5 scoops whey protein', '30g dextrose or honey', '300ml water', 'Ice cubes'],
    steps: ['Add all ingredients to shaker bottle', 'Shake vigorously for 30 seconds', 'Consume within 30 minutes of workout'],
    tags: ['protein-shake', 'post-workout', 'recovery', 'quick'],
  },
  {
    name: 'Chocolate Milk Recovery',
    description: 'The ultimate post-workout recovery drink',
    mealType: 'post-workout',
    difficulty: 'beginner',
    prepTime: 2,
    cookTime: 0,
    servings: 1,
    calories: 280,
    protein: 16,
    carbs: 42,
    fat: 6,
    fiber: 0,
    ingredients: ['500ml chocolate milk', '1 scoop chocolate protein powder', 'Ice'],
    steps: ['Combine chocolate milk and protein powder in shaker', 'Shake until mixed', 'Pour over ice and drink immediately after workout'],
    tags: ['chocolate-milk', 'post-workout', 'recovery', 'quick'],
  },
  {
    name: 'Chicken and Sweet Potato Bowl',
    description: 'Perfect post-workout meal with lean protein and carbs',
    mealType: 'post-workout',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 15,
    servings: 1,
    calories: 420,
    protein: 40,
    carbs: 45,
    fat: 8,
    fiber: 5,
    ingredients: ['200g chicken breast', '1 sweet potato cubed', '1 cup spinach', '1 tbsp olive oil', 'Salt and pepper'],
    steps: ['Season and grill chicken 6 minutes per side', 'Cube sweet potato, microwave 8 minutes or roast', 'Saute spinach in oil until wilted', 'Slice chicken and serve with sweet potato and spinach'],
    tags: ['chicken', 'sweet-potato', 'post-workout', 'recovery', 'whole-food'],
  },
  {
    name: 'Tuna and Rice Bowl',
    description: 'Quick post-workout tuna bowl with rice and avocado',
    mealType: 'post-workout',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    calories: 450,
    protein: 38,
    carbs: 45,
    fat: 12,
    fiber: 4,
    ingredients: ['1 can tuna', '1 cup cooked white rice', '1/2 avocado', '1 tbsp soy sauce', '1 tsp sesame seeds', '1 sheet nori'],
    steps: ['Flake tuna and mix with soy sauce', 'Serve tuna over warm rice', 'Top with avocado, sesame seeds, and torn nori'],
    tags: ['tuna', 'rice', 'post-workout', 'recovery', 'quick'],
  },
  {
    name: 'Egg and Potato Scramble',
    description: 'Post-workout egg scramble with potatoes for carb replenishment',
    mealType: 'post-workout',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 12,
    servings: 1,
    calories: 400,
    protein: 28,
    carbs: 35,
    fat: 16,
    fiber: 3,
    ingredients: ['3 eggs', '1 potato cubed', '1/4 onion', '1 tbsp olive oil', 'Salt, pepper, paprika'],
    steps: ['Cube and microwave potato 4 minutes', 'Fry potato cubes in oil until golden', 'Add onion, cook 2 minutes', 'Scramble in eggs, cook until set', 'Season and serve'],
    tags: ['eggs', 'potato', 'post-workout', 'recovery'],
  },
  {
    name: 'Beef and Sweet Potato Hash',
    description: 'Ground beef and sweet potato hash for recovery',
    mealType: 'post-workout',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    calories: 380,
    protein: 30,
    carbs: 30,
    fat: 16,
    fiber: 5,
    ingredients: ['200g ground beef', '1 sweet potato cubed', '1/2 onion diced', '1 bell pepper diced', '1 tbsp olive oil', '1 tsp chili powder', 'Salt and pepper'],
    steps: ['Microwave sweet potato cubes 5 minutes', 'Brown beef in oil, remove', 'Cook onion and pepper 3 minutes', 'Add sweet potato and beef back', 'Season with chili powder, cook 5 minutes'],
    tags: ['beef', 'sweet-potato', 'post-workout', 'recovery'],
  },
  {
    name: 'Greek Yogurt with Honey and Walnuts',
    description: 'Simple post-workout Greek yogurt bowl',
    mealType: 'post-workout',
    difficulty: 'beginner',
    prepTime: 3,
    cookTime: 0,
    servings: 1,
    calories: 280,
    protein: 22,
    carbs: 28,
    fat: 10,
    fiber: 2,
    ingredients: ['200g Greek yogurt', '1 tbsp honey', '1/4 cup walnuts', '1/2 cup mixed berries'],
    steps: ['Scoop yogurt into bowl', 'Drizzle honey', 'Top with walnuts and berries', 'Enjoy within an hour of workout'],
    tags: ['yogurt', 'post-workout', 'recovery', 'quick'],
  },
  {
    name: 'Protein Oatmeal',
    description: 'Protein-packed oatmeal for post-workout recovery',
    mealType: 'post-workout',
    difficulty: 'beginner',
    prepTime: 2,
    cookTime: 5,
    servings: 1,
    calories: 350,
    protein: 28,
    carbs: 45,
    fat: 6,
    fiber: 5,
    ingredients: ['1/2 cup rolled oats', '1 scoop protein powder', '1 cup milk', '1/2 banana sliced', '1 tbsp peanut butter'],
    steps: ['Cook oats with milk according to package', 'Stir in protein powder until smooth', 'Top with banana and peanut butter', 'Eat immediately'],
    tags: ['oats', 'protein', 'post-workout', 'recovery', 'warm'],
  },
  {
    name: 'Turkey and Cheese Roll-Ups',
    description: 'Quick high-protein roll-ups for immediate post-workout',
    mealType: 'post-workout',
    difficulty: 'beginner',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 260,
    protein: 30,
    carbs: 4,
    fat: 14,
    fiber: 0,
    ingredients: ['150g sliced turkey', '2 slices Swiss cheese', '1 tbsp mustard', '1/2 apple sliced'],
    steps: ['Lay turkey slices flat', 'Place cheese on turkey', 'Roll up tightly', 'Serve with apple slices'],
    tags: ['turkey', 'cheese', 'post-workout', 'high-protein', 'low-carb'],
  },
  {
    name: 'Cottage Cheese and Fruit Bowl',
    description: 'High-protein cottage cheese with fresh fruit for post-workout',
    mealType: 'post-workout',
    difficulty: 'beginner',
    prepTime: 3,
    cookTime: 0,
    servings: 1,
    calories: 250,
    protein: 24,
    carbs: 28,
    fat: 4,
    fiber: 3,
    ingredients: ['200g cottage cheese', '1/2 cup pineapple', '1/2 cup strawberries', '1 tbsp chia seeds'],
    steps: ['Place cottage cheese in bowl', 'Top with pineapple and strawberries', 'Sprinkle chia seeds', 'Enjoy immediately'],
    tags: ['cottage-cheese', 'fruit', 'post-workout', 'high-protein'],
  },
];

export async function seedRecipes(): Promise<number> {
  const existing = await prisma.recipe.findMany({ select: { name: true } });
  const existingNames = new Set(existing.map((r) => r.name));
  const newRecipes: Array<{
    name: string;
    description: string;
    mealType: string;
    difficulty: string;
    prepTime: number;
    cookTime: number | null;
    servings: number;
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    fiber: number | null;
    ingredients: string;
    steps: string;
    tags: string;
  }> = [];

  for (const recipe of RECIPES) {
    if (existingNames.has(recipe.name)) continue;
    newRecipes.push({
      name: recipe.name,
      description: recipe.description,
      mealType: recipe.mealType,
      difficulty: recipe.difficulty,
      prepTime: recipe.prepTime,
      cookTime: recipe.cookTime,
      servings: recipe.servings,
      calories: recipe.calories,
      protein: recipe.protein,
      carbs: recipe.carbs,
      fat: recipe.fat,
      fiber: recipe.fiber,
      ingredients: JSON.stringify(recipe.ingredients),
      steps: JSON.stringify(recipe.steps),
      tags: JSON.stringify(recipe.tags),
    });
  }

  if (newRecipes.length > 0) {
    await prisma.recipe.createMany({ data: newRecipes, skipDuplicates: true });
  }

  return newRecipes.length;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  seedRecipes()
    .then((count) => {
      console.log(`Recipes seeded: ${count}`);
      return prisma.$disconnect();
    })
    .catch((e) => {
      console.error(e);
      return prisma.$disconnect().then(() => process.exit(1));
    });
}
